[package]
name = "nettle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
almost-raft = "0.3.0"
eyre = "0.6.8"
log4rs = "1.1.1"
